#include "unity.h"

extern void test_jogo_detecta_vitoria_em_linha(void);
extern void test_jogo_rejeita_casa_ocupada(void);
extern void test_jogo_detecta_empate(void);
extern void test_ia_faz_jogada_vencedora(void);
extern void test_ia_bloqueia_vitoria_do_jogador(void);
extern void test_mapa_do_teclado_documentado(void);
extern void test_linha_do_tabuleiro_cabe_no_oled(void);
extern void test_linha_do_tabuleiro_expandida_preserva_espacamento(void);
extern void test_mpu6050_constantes_do_driver(void);
extern void test_mpu6050_converte_bytes_assinados(void);
extern void test_mpu6050_converte_vetor_de_aceleracao(void);
extern void test_mpu6050_rejeita_argumentos_invalidos(void);
extern void test_coleta_mpu6050_cabecalho_e_taxa(void);
extern void test_coleta_mpu6050_labels_aceitos(void);
extern void test_coleta_mpu6050_formata_linha_csv_com_negativos(void);
extern void test_coleta_mpu6050_rejeita_linha_csv_invalida(void);
extern void test_coleta_mpu6050_configura_estado_inicial(void);
extern void test_coleta_mpu6050_pipeline_bytes_ate_csv(void);
extern void test_serie_temporal_buffer_circular(void);
extern void test_serie_temporal_calcula_features(void);
extern void test_serie_temporal_preprocessa_int8(void);
extern void test_gesto_heuristica_ignora_repouso(void);
extern void test_gesto_heuristica_detecta_confirmacao(void);
extern void test_gesto_detector_aplica_debounce(void);
extern void test_gesto_tflite_inicia_modelo_embarcado(void);
extern void test_gesto_tflite_classifica_janela_de_confirmacao(void);
extern void test_gesto_tflite_fallback_sem_modelo(void);
extern void test_auto_scan_inicia_na_primeira_casa_livre(void);
extern void test_auto_scan_avanca_e_pula_ocupadas(void);
extern void test_auto_scan_confirmar_aplica_jogada(void);
extern void test_ia_tflite_converte_tabuleiro_para_vetor(void);
extern void test_ia_tflite_mascara_casas_ocupadas(void);
extern void test_ia_tflite_fallback_quando_inferencia_falha(void);
extern void test_ia_tflite_prefere_vitoria_imediata(void);

void app_main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_jogo_detecta_vitoria_em_linha);
    RUN_TEST(test_jogo_rejeita_casa_ocupada);
    RUN_TEST(test_jogo_detecta_empate);
    RUN_TEST(test_ia_faz_jogada_vencedora);
    RUN_TEST(test_ia_bloqueia_vitoria_do_jogador);
    RUN_TEST(test_mapa_do_teclado_documentado);
    RUN_TEST(test_linha_do_tabuleiro_cabe_no_oled);
    RUN_TEST(test_linha_do_tabuleiro_expandida_preserva_espacamento);
    RUN_TEST(test_mpu6050_constantes_do_driver);
    RUN_TEST(test_mpu6050_converte_bytes_assinados);
    RUN_TEST(test_mpu6050_converte_vetor_de_aceleracao);
    RUN_TEST(test_mpu6050_rejeita_argumentos_invalidos);
    RUN_TEST(test_coleta_mpu6050_cabecalho_e_taxa);
    RUN_TEST(test_coleta_mpu6050_labels_aceitos);
    RUN_TEST(test_coleta_mpu6050_formata_linha_csv_com_negativos);
    RUN_TEST(test_coleta_mpu6050_rejeita_linha_csv_invalida);
    RUN_TEST(test_coleta_mpu6050_configura_estado_inicial);
    RUN_TEST(test_coleta_mpu6050_pipeline_bytes_ate_csv);
    RUN_TEST(test_serie_temporal_buffer_circular);
    RUN_TEST(test_serie_temporal_calcula_features);
    RUN_TEST(test_serie_temporal_preprocessa_int8);
    RUN_TEST(test_gesto_heuristica_ignora_repouso);
    RUN_TEST(test_gesto_heuristica_detecta_confirmacao);
    RUN_TEST(test_gesto_detector_aplica_debounce);
    RUN_TEST(test_gesto_tflite_inicia_modelo_embarcado);
    RUN_TEST(test_gesto_tflite_classifica_janela_de_confirmacao);
    RUN_TEST(test_gesto_tflite_fallback_sem_modelo);
    RUN_TEST(test_auto_scan_inicia_na_primeira_casa_livre);
    RUN_TEST(test_auto_scan_avanca_e_pula_ocupadas);
    RUN_TEST(test_auto_scan_confirmar_aplica_jogada);
    RUN_TEST(test_ia_tflite_converte_tabuleiro_para_vetor);
    RUN_TEST(test_ia_tflite_mascara_casas_ocupadas);
    RUN_TEST(test_ia_tflite_fallback_quando_inferencia_falha);
    RUN_TEST(test_ia_tflite_prefere_vitoria_imediata);
    UNITY_END();
}
