#include "unity.h"

extern void test_jogo_detecta_vitoria_em_linha(void);
extern void test_jogo_rejeita_casa_ocupada(void);
extern void test_jogo_detecta_empate(void);
extern void test_auditoria_serializa_tabuleiro_com_pontos_para_vazio(void);
extern void test_auditoria_detecta_vitoria_do_jogador_e_linha(void);
extern void test_auditoria_nao_declara_vencedor_antes_de_trinca_real(void);
extern void test_auditoria_converte_jogada_para_posicao_1a9(void);
extern void test_interacao_libera_teclado_quando_sensor_de_presenca_indisponivel(void);
extern void test_interacao_bloqueia_teclado_enquanto_presenca_nao_tem_leitura_valida(void);
extern void test_interacao_bloqueia_teclado_quando_jogador_ausente(void);
extern void test_interacao_libera_teclado_quando_jogador_presente(void);
extern void test_interacao_ignora_todos_os_botoes_quando_jogador_ausente(void);
extern void test_interacao_nao_bloqueia_ausencia_de_tecla(void);
extern void test_interacao_libera_todos_os_botoes_quando_jogador_presente(void);
extern void test_estatisticas_lcd_mostra_media_em_decimos_de_segundo(void);
extern void test_estatisticas_lcd_mostra_zero_sem_jogadas(void);
extern void test_estatisticas_lcd_preserva_largura_de_16_colunas(void);
extern void test_mapa_do_teclado_documentado(void);
extern void test_linha_do_tabuleiro_cabe_no_oled(void);
extern void test_linha_do_tabuleiro_expandida_preserva_espacamento(void);
extern void test_lcd1602_scroll_autores_primeira_janela(void);
extern void test_lcd1602_scroll_autores_move_para_esquerda(void);
extern void test_lcd1602_scroll_autores_reinicia_com_espaco(void);
extern void test_hcsr04_converte_echo_para_distancia(void);
extern void test_hcsr04_valida_faixa_de_distancia(void);
extern void test_hcsr04_constantes_do_sensor(void);
extern void test_hcsr04_rejeita_argumentos_invalidos(void);
extern void test_ldr_detecta_ambiente_escuro_por_limiar(void);
extern void test_ldr_iluminacao_automatica_ativa_so_sem_modo_manual(void);
extern void test_ldr_histerese_liga_no_escuro_e_desliga_no_claro(void);
extern void test_ldr_constantes_do_adc(void);
extern void test_ldr_configura_estado_padrao(void);
extern void test_ldr_rejeita_argumentos_invalidos(void);
extern void test_ia_tflite_converte_tabuleiro_para_vetor(void);
extern void test_ia_tflite_mascara_casas_ocupadas(void);
extern void test_ia_tflite_nao_usa_fallback_quando_inferencia_falha(void);
extern void test_ia_tflite_prefere_vitoria_imediata(void);
extern void test_ia_tflite_header_tem_metadados_de_treinamento(void);
extern void test_presenca_compacto_detecta_jogador_proximo(void);
extern void test_presenca_compacto_detecta_ausencia(void);
extern void test_presenca_compacto_score_cai_com_distancia(void);
extern void test_presenca_tflite_inicia_com_modelo_int8_real(void);
extern void test_presenca_tflite_classifica_amostra_proxima(void);
extern void test_presenca_tflite_classifica_amostra_distante(void);
extern void test_presenca_tflite_rejeita_distancias_invalidas_antes_da_inferencia(void);
extern void test_presenca_tflite_fallback_compacto_quando_modelo_nulo(void);
extern void test_presenca_timeout_do_hcsr04_substitui_leitura_antiga_por_ausencia(void);
extern void test_presenca_quatro_metros_eh_ausente_e_bloqueia_teclado(void);
extern void test_presenca_modelo_embarcado_tem_flatbuffer_real(void);
extern void test_presenca_header_tem_metadados_de_treinamento(void);

/* Testes de fidelidade ao Alpha0 */
extern void test_alpha0_jogador_sempre_usa_O(void);
extern void test_alpha0_computador_sempre_usa_X(void);
extern void test_alpha0_tabuleiro_inicial_mostra_numeros(void);
extern void test_alpha0_numeros_desaparecem_apos_primeira_jogada(void);
extern void test_alpha0_rejeita_posicao_ocupada(void);
extern void test_alpha0_mapeamento_posicao_1a9(void);
extern void test_alpha0_rejeita_posicao_invalida(void);
extern void test_alpha0_vitoria_todas_combinacoes(void);
extern void test_alpha0_empate_tabuleiro_cheio(void);
extern void test_alpha0_placar_inicio_zerado(void);
extern void test_alpha0_placar_zerar_preserva_tabuleiro(void);
extern void test_alpha0_ia_nunca_joga_em_casa_ocupada(void);
extern void test_alpha0_tabuleiro_resetado_entre_partidas(void);
extern void test_alpha0_formato_tabuleiro_expandido(void);
extern void test_alpha0_nomes_algoritmos_lcd(void);

void app_main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_jogo_detecta_vitoria_em_linha);
    RUN_TEST(test_jogo_rejeita_casa_ocupada);
    RUN_TEST(test_jogo_detecta_empate);
    RUN_TEST(test_auditoria_serializa_tabuleiro_com_pontos_para_vazio);
    RUN_TEST(test_auditoria_detecta_vitoria_do_jogador_e_linha);
    RUN_TEST(test_auditoria_nao_declara_vencedor_antes_de_trinca_real);
    RUN_TEST(test_auditoria_converte_jogada_para_posicao_1a9);
    RUN_TEST(test_interacao_libera_teclado_quando_sensor_de_presenca_indisponivel);
    RUN_TEST(test_interacao_bloqueia_teclado_enquanto_presenca_nao_tem_leitura_valida);
    RUN_TEST(test_interacao_bloqueia_teclado_quando_jogador_ausente);
    RUN_TEST(test_interacao_libera_teclado_quando_jogador_presente);
    RUN_TEST(test_interacao_ignora_todos_os_botoes_quando_jogador_ausente);
    RUN_TEST(test_interacao_nao_bloqueia_ausencia_de_tecla);
    RUN_TEST(test_interacao_libera_todos_os_botoes_quando_jogador_presente);
    RUN_TEST(test_estatisticas_lcd_mostra_media_em_decimos_de_segundo);
    RUN_TEST(test_estatisticas_lcd_mostra_zero_sem_jogadas);
    RUN_TEST(test_estatisticas_lcd_preserva_largura_de_16_colunas);
    RUN_TEST(test_mapa_do_teclado_documentado);
    RUN_TEST(test_linha_do_tabuleiro_cabe_no_oled);
    RUN_TEST(test_linha_do_tabuleiro_expandida_preserva_espacamento);
    RUN_TEST(test_lcd1602_scroll_autores_primeira_janela);
    RUN_TEST(test_lcd1602_scroll_autores_move_para_esquerda);
    RUN_TEST(test_lcd1602_scroll_autores_reinicia_com_espaco);
    RUN_TEST(test_hcsr04_converte_echo_para_distancia);
    RUN_TEST(test_hcsr04_valida_faixa_de_distancia);
    RUN_TEST(test_hcsr04_constantes_do_sensor);
    RUN_TEST(test_hcsr04_rejeita_argumentos_invalidos);
    RUN_TEST(test_ldr_detecta_ambiente_escuro_por_limiar);
    RUN_TEST(test_ldr_iluminacao_automatica_ativa_so_sem_modo_manual);
    RUN_TEST(test_ldr_histerese_liga_no_escuro_e_desliga_no_claro);
    RUN_TEST(test_ldr_constantes_do_adc);
    RUN_TEST(test_ldr_configura_estado_padrao);
    RUN_TEST(test_ldr_rejeita_argumentos_invalidos);
    RUN_TEST(test_ia_tflite_converte_tabuleiro_para_vetor);
    RUN_TEST(test_ia_tflite_mascara_casas_ocupadas);
    RUN_TEST(test_ia_tflite_nao_usa_fallback_quando_inferencia_falha);
    RUN_TEST(test_ia_tflite_prefere_vitoria_imediata);
    RUN_TEST(test_ia_tflite_header_tem_metadados_de_treinamento);
    RUN_TEST(test_presenca_compacto_detecta_jogador_proximo);
    RUN_TEST(test_presenca_compacto_detecta_ausencia);
    RUN_TEST(test_presenca_compacto_score_cai_com_distancia);
    RUN_TEST(test_presenca_tflite_inicia_com_modelo_int8_real);
    RUN_TEST(test_presenca_tflite_classifica_amostra_proxima);
    RUN_TEST(test_presenca_tflite_classifica_amostra_distante);
    RUN_TEST(test_presenca_tflite_rejeita_distancias_invalidas_antes_da_inferencia);
    RUN_TEST(test_presenca_tflite_fallback_compacto_quando_modelo_nulo);
    RUN_TEST(test_presenca_timeout_do_hcsr04_substitui_leitura_antiga_por_ausencia);
    RUN_TEST(test_presenca_quatro_metros_eh_ausente_e_bloqueia_teclado);
    RUN_TEST(test_presenca_modelo_embarcado_tem_flatbuffer_real);
    RUN_TEST(test_presenca_header_tem_metadados_de_treinamento);

    /* Testes Alpha0 */
    RUN_TEST(test_alpha0_jogador_sempre_usa_O);
    RUN_TEST(test_alpha0_computador_sempre_usa_X);
    RUN_TEST(test_alpha0_tabuleiro_inicial_mostra_numeros);
    RUN_TEST(test_alpha0_numeros_desaparecem_apos_primeira_jogada);
    RUN_TEST(test_alpha0_rejeita_posicao_ocupada);
    RUN_TEST(test_alpha0_mapeamento_posicao_1a9);
    RUN_TEST(test_alpha0_rejeita_posicao_invalida);
    RUN_TEST(test_alpha0_vitoria_todas_combinacoes);
    RUN_TEST(test_alpha0_empate_tabuleiro_cheio);
    RUN_TEST(test_alpha0_placar_inicio_zerado);
    RUN_TEST(test_alpha0_placar_zerar_preserva_tabuleiro);
    RUN_TEST(test_alpha0_ia_nunca_joga_em_casa_ocupada);
    RUN_TEST(test_alpha0_tabuleiro_resetado_entre_partidas);
    RUN_TEST(test_alpha0_formato_tabuleiro_expandido);
    RUN_TEST(test_alpha0_nomes_algoritmos_lcd);
    UNITY_END();
}
